### PR TITLE
Feature/poky update

### PR DESCRIPTION
**Pull request by skovbakke**
We update to kubernetes 1.22.1. This requires an update to the kubeadm config api.

This PR goes along with https://github.com/distributed-technologies/mukube/pull/60

### CODE REVIEW

**Review by jacobcrawford — CHANGES_REQUESTED** [review]
Please paste a screenshot of a successful test run.

**Comment by skovbakke** [comment]
> What is the KubeletConfig for?

Configuring the kubelet 😁

See [the reference linked in the commit message](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3):
_"The KubeletConfiguration type should be used to change the configurations that will be passed to all kubelet instances deployed in the cluster. If this object is not provided or provided only partially, kubeadm applies defaults."_

Basically, with the update, passing command line arguments has been deprecated for many of the configuration parameters.

**Review by klausenbusk — APPROVED** [review]
LGTM 🎉

Tested, see: https://github.com/distributed-technologies/mukube/pull/60#pullrequestreview-863894627

**Review by jacobcrawford — APPROVED** [review]
As Kristian has tested it I believe it works. I guess the kubelet reads the KubeletConfiguration from some path and it is not necessary to parse it explicitly? 
Anyway LGTM

**Pull request merged**
